env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://db-card-staging.csw30454.workers.dev
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://db-card-staging.csw30454.workers.dev
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: /zap/wrk/docs/security/scan-reports/2026-02-01-owasp-zap-after-fix.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
